# This file defines the layout and content of the monitor screens.
# You can customize what is displayed by editing this file.

# Inactivity timeout in seconds. Set to 0 to disable the screen saver.
screen_timeout: 60

colors:
  title_background: "BLACK"
  title_text: "WHITE"
  content_background: "#2a412a"
  widget_default: "WHITE"
  nav_buttons: "WHITE"

fonts:
  large:
    path: "Voltaire-Regular.ttf"
    size: 24
  medium:
    path: "Voltaire-Regular.ttf"
    size: 18
  small:
    path: "Voltaire-Regular.ttf"
    size: 14

screens:
  - type: "hero"
    image_path: "placeholder.png"

  - title: "System Overview"
    widgets:
      - type: "line_item"
        label: "Hostname:"
        position: [12, 50]
        data_source: "get_hostname"
        data_x_offset: 100
        label_color: "#c29b4a"
      - type: "line_item"
        label: "Uptime:"
        position: [12, 76]
        data_source: "get_system_uptime"
        data_x_offset: 100
        label_color: "#c29b4a"
      - type: "line_item"
        position: [12, 102]
        label: "CPU Temp:"
        data_source: "get_cpu_temperature"
        font: "medium"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        position: [12, 128]
        label: "CPU Usage:"
        data_source: "get_cpu_usage"
        font: "medium"
        data_x_offset: 100
        label_color: "#c29b4a"
      - type: "dynamic_text"
        position: [172, 132]
        template: "@ {data}"
        data_source: "get_cpu_frequency"
        font: "small"
        color: "GRAY"
      - type: "line_item"
        position: [12, 154]
        label: "RAM Usage:"
        data_source: "get_ram_usage_percent"
        font: "medium"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "static_text"
        position: [172, 158]
        data_source: "get_ram_usage_summary"
        font: "small"
        color: "GRAY"
      - type: "line_item"
        position: [12, 180]
        label: "Disk Usage:"
        data_source: "get_disk_usage_percent"
        font: "medium"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "static_text"
        position: [172, 184]
        data_source: "get_disk_usage_summary"
        font: "small"
        color: "GRAY"
      - type: "dynamic_text"
        position: [6, 216]
        template: "IP: {data}"
        data_source: "get_ip_address"
        font: "medium"
        color: "#4a6d4a"
      - type: "static_text"
        position: [260, 216]
        data_source: "get_current_time"
        font: "medium"
        color: "GRAY"

  - title: "Network Details"
    widgets:
      - type: "line_item"
        label: "eth0 IP:"
        position: [12, 50]
        data_source:
          name: "get_interface_ip"
          args: ["eth0"]
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "eth0 MAC:"
        position: [12, 76]
        data_source:
          name: "get_interface_mac"
          args: ["eth0"]
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "Rx Rate:"
        position: [12, 102]
        data_source:
          name: "get_interface_rx"
          args: ["eth0"]
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "Tx Rate:"
        position: [12, 128]
        data_source:
          name: "get_interface_tx"
          args: ["eth0"]
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "Tailscale IP:"
        position: [12, 154]
        data_source:
          name: "get_interface_ip"
          args: ["tailscale0"]
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "dynamic_text"
        position: [6, 216]
        template: "Uptime: {data}"
        data_source: "get_system_uptime"
        font: "medium"
        color: "#4a6d4a"
      - type: "static_text"
        position: [260, 216]
        data_source: "get_current_time"
        font: "medium"
        color: "GRAY"

  - title: "Hardware & OS"
    widgets:
      - type: "line_item"
        label: "OS:"
        position: [12, 50]
        data_source: "get_os_info"
        label_color: "#c29b4a"
        data_x_offset: 60
      - type: "line_item"
        label: "Kernel:"
        position: [12, 76]
        data_source: "get_kernel_info"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "CPU Cores:"
        position: [12, 102]
        data_source: "get_cpu_cores"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "CPU Max Freq:"
        position: [12, 128] 
        data_source: "get_cpu_max_frequency"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "line_item"
        label: "Total RAM:"
        position: [12, 154] 
        data_source: "get_ram_total"
        label_color: "#c29b4a"
        data_x_offset: 100
      - type: "dynamic_text"
        position: [6, 216]
        template: "Uptime: {data}"
        data_source: "get_system_uptime"
        font: "medium"
        color: "#4a6d4a"
      - type: "static_text"
        position: [260, 216]
        data_source: "get_current_time"
        font: "medium"
        color: "GRAY"