# This file defines the layout and content of the monitor screens.
# You can customize what is displayed by editing this file.

# Inactivity timeout in seconds. Set to 0 to disable the screen saver.
screen_timeout: 60

colors:
  title_background: "BLACK"
  title_text: "WHITE"
  content_background: "#2a412a"
  widget_default: "WHITE"
  nav_buttons: "WHITE"

fonts:
  large:
    path: "Voltaire-Regular.ttf"
    size: 24
  medium:
    path: "Voltaire-Regular.ttf"
    size: 18
  small:
    path: "Voltaire-Regular.ttf"
    size: 14

screens:
  - title: "System Overview"
    widgets:
      # A 'line_item' displays a label and a value on the same line.
      - type: "line_item"
        position: [40, 50]
        label: "CPU Temp:"
        data_source: "get_cpu_temperature"
        font: "medium"
        color: "#c29b4a"
        data_x_offset: 140
      - type: "line_item"
        position: [40, 80]
        label: "CPU Usage:"
        data_source: "get_cpu_usage"
        font: "medium"
        color: "#c29b4a"
        data_x_offset: 140
      # A 'line_item_with_sub' is for data that returns two parts, like usage % and total size.
      - type: "line_item_with_sub"
        position: [40, 110]
        label: "RAM Usage:"
        data_source: "get_ram_info"
        font: "medium"
        color: "#c29b4a"
        sub_font: "small"
        sub_color: "GRAY"
        data_x_offset: 140
        sub_y_offset: 20
      # A 'dynamic_text' widget displays formatted text from a data source.
      - type: "dynamic_text"
        position: [10, 210]
        template: "IP: {data}"
        data_source: "get_ip_address"
        font: "medium"
        color: "#4a6d4a"
      # A 'static_text' widget displays text from a function that doesn't need a label.
      - type: "static_text"
        position: [230, 210]
        data_source: "get_current_time"
        font: "medium"
        color: "WHITE"

  - title: "Storage & Network"
    # color: "CYAN" # Optional: overrides the default colors.title_text
    widgets:
      - type: "line_item"
        label: "Uptime:"
        position: [10, 50]
        data_source: "get_system_uptime"
      - type: "line_item_with_sub"
        position: [40, 60]
        label: "Disk Usage:"
        data_source: "get_disk_space"
        font: "medium"
        color: "#c29b4a"
        sub_font: "small"
        sub_color: "GRAY"
        data_x_offset: 180
        sub_y_offset: 20
      - type: "static_text"
        position: [230, 210]
        data_source: "get_current_time"
        font: "medium"
        color: "WHITE"

  - title: "Network Details"
    widgets:
      - type: "line_item"
        label: "eth0 IP:"
        position: [40, 50]
        data_source:
          name: "get_interface_ip"
          args: ["eth0"]
        data_x_offset: 120
      - type: "line_item"
        label: "eth0 MAC:"
        position: [40, 80]
        data_source:
          name: "get_interface_mac"
          args: ["eth0"]
        data_x_offset: 120
      - type: "line_item"
        label: "Tailscale IP:"
        position: [40, 110]
        data_source:
          name: "get_interface_ip"
          args: ["tailscale0"]
        data_x_offset: 120
      - type: "line_item"
        label: "Rx:"
        position: [40, 140]
        data_source:
          name: "get_interface_rx"
          args: ["eth0"]
        data_x_offset: 120
      - type: "line_item"
        label: "Tx:"
        position: [40, 170]
        data_source:
          name: "get_interface_tx"
          args: ["eth0"]
        data_x_offset: 120
      - type: "static_text"
        position: [230, 210]
        data_source: "get_current_time"
        font: "medium"
        color: "WHITE"

  - title: "Host Info"
    widgets:
      - type: "line_item"
        label: "Hostname:"
        position: [40, 50]
        data_source: "get_hostname"
        data_x_offset: 140
      - type: "dynamic_text"
        position: [40, 80]
        template: "{data}"
        data_source: "get_os_info"
        font: "small"
      - type: "line_item"
        label: "Kernel:"
        position: [40, 110]
        data_source: "get_kernel_info"
        data_x_offset: 140
      - type: "line_item"
        label: "CPU Cores:"
        position: [40, 140]
        data_source: "get_cpu_cores"
        data_x_offset: 140
      - type: "line_item_with_sub"
        label: "CPU Freq:"
        position: [40, 170]
        data_source: "get_cpu_frequency"
        data_x_offset: 140
      - type: "static_text"
        position: [230, 210]
        data_source: "get_current_time"
        font: "medium"
        color: "WHITE"
      - type: "line_item"
        label: "CPU Max Freq:"
        position: [40, 210] 
        data_source: "get_cpu_max_frequency"
        data_x_offset: 140



      - type: "line_item_with_sub"
        position: [40, 60]
        label: "Disk Usage:"
        data_source: "get_disk_space"
        font: "medium"
        color: "#c29b4a"
        sub_font: "small"
        sub_color: "GRAY"
        data_x_offset: 180
        sub_y_offset: 20